name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
      uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 使用官方 Gradle Build Action，指定版本，不依赖本地 wrapper
      - name: Build with Gradle 8.7
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          arguments: build

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: APKs
          path: |
            mobile/build/outputs/apk/debug/*.apk
            wear/build/outputs/apk/debug/*.apk
