name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 设置 JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 设置 Gradle（无需仓库 gradlew）
      - name: Set up Gradle 8.7
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      # 获取最新 tag 并递增版本号
      - name: Determine next version
        id: next_version
        run: |
          latest=$(git tag --sort=-creatordate | head -n1)
          echo "Latest tag: $latest"
          if [ -z "$latest" ]; then
            next="v1.0.0"
          else
            IFS='.' read -r major minor patch <<<"${latest#v}"
            patch=$((patch + 1))
            next="v${major}.${minor}.${patch}"
          fi
          echo "Next version: $next"
          echo "NEXT_VERSION=$next" >> $GITHUB_ENV

          # 自动生成 versionCode（用秒数保证递增）
          version_code=$(date +%s)
          echo "VERSION_CODE=$version_code" >> $GITHUB_ENV

      # 更新 build.gradle 中 versionCode 和 versionName
      - name: Update Gradle version
        run: |
          sed -i "s/versionCode [0-9]\+/versionCode $VERSION_CODE/" mobile/build.gradle
          sed -i "s/versionName \".*\"/versionName \"$NEXT_VERSION\"/" mobile/build.gradle
          sed -i "s/versionCode [0-9]\+/versionCode $VERSION_CODE/" wear/build.gradle
          sed -i "s/versionName \".*\"/versionName \"$NEXT_VERSION\"/" wear/build.gradle

      # 构建 APK
      - name: Build APK
        run: gradle build --warning-mode all || true
      # 上传 APK 作为 artifact
      - name: Upload APKs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: APKs
          path: |
            mobile/build/outputs/apk/debug/*.apk
            wear/build/outputs/apk/debug/*.apk

      # 创建 Release
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.NEXT_VERSION }}
          name: "AlarmSyncApp ${{ env.NEXT_VERSION }}"
          body: "Automated release from GitHub Actions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 上传 APK 到 Release
      - name: Upload APKs to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            mobile/build/outputs/apk/debug/*.apk
            wear/build/outputs/apk/debug/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
