name: Android CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Debug APKs
        run: ./gradlew assembleDebug

      - name: Set version and tag
        id: versioning
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.0.0")
          BASE=${LATEST_TAG%.*}
          PATCH=${LATEST_TAG##*.}
          NEXT_VERSION="$BASE.$((PATCH+1))"
          echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV

      - name: Create and push Git tag
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ env.NEXT_VERSION }}
          git push origin ${{ env.NEXT_VERSION }}

---

name: Release CI

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-tags: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            mobile/build/outputs/apk/debug/*.apk
            wear/build/outputs/apk/debug/*.apk
